name: tn_checkin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  
  # Location services
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  
  # Maps
  google_maps_flutter: ^2.9.0
  
  # State management & architecture
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  get_it: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
