// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvMCJq3G9HPr4mAI0MszdzT1cfnbaiHPM',
    appId: '1:552632887204:android:9bcb4f2b9977e1bb150331',
    messagingSenderId: '552632887204',
    projectId: 'my-notes-ssoad',
    storageBucket: 'my-notes-ssoad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOR7hBhKhfH0hgsOTIehCbeJTaCEEUNTg',
    appId: '1:552632887204:ios:b757a3c3af1f22e5150331',
    messagingSenderId: '552632887204',
    projectId: 'my-notes-ssoad',
    storageBucket: 'my-notes-ssoad.firebasestorage.app',
    androidClientId: '552632887204-64isfgvsgbk9k755tf9flch46f67qnvr.apps.googleusercontent.com',
    iosClientId: '552632887204-pcs2qc54k34ntquk4fuoitead9dos69n.apps.googleusercontent.com',
    iosBundleId: 'com.example.tnCheckin',
  );
}
